txt = input("Digita algo aí:")
print('o tipo primitivo da entrada é:', type(txt))
print('é alphanumérico?', txt.isalnum())
print('é um numeral?', txt.isnumeric())
print('é alfabético?:', txt.isalpha())
print('é um digito:', txt.isdigit())
print('está em maiusculo?', txt.isupper())
print('está em minusculo?', txt.islower())
print('é um número decimal?', txt.isdecimal())
print('é um titulo?', txt.istitle())
